### ISSUE TITLE
Make ffprobe optional

### ISSUE THREAD

**Issue by Geczy** [strafe/grumi#1]

**Comment by strafe** [comment]
`ffprobe` is only required when uploading videos (which is barely supported by the Imgur API in the first place). Since it's bundled with `ffmpeg` and readily available I'm not going to drop it at this time.

**Comment by strafe** [comment]
Turns out I ended up making a lot more changes than I though. `ffprobe` is currently removed, and the API is generating errors for videos that are too long at the moment.

Unfortunately this means you need to wait for the whole video to upload before it fails. Ideally an optional `ffprobe` check (if installed) would be ideal to reduce headaches.

**Comment by strafe** [comment]
Local sanity checks were added back in https://github.com/strafe/grumi/commit/77a3e8c56f81d617348af84acfd48a2f19a92219. This time video length is only checked locally if `ffprobe` is installed, otherwise Imgur's API will throw the error during the upload.

---
Local:
```
grumi: 61s.mp4: Failed to process (error: Video too long 60s max).
```

Imgur API fallback:
```
grumi: 61s.mp4: Failed to upload (error: File exceeds max duration).
```
